var d=!0,e=null,h=!1;function j(a){return function(){return this[a]}}var l;
function m(a,b,c){this.extend(m,google.e.ea);this.a=a;this.b=[];this.h=[];this.va=[53,56,66,78,90];this.m=[];this.J=h;c=c||{};this.i=c.gridSize||60;this.o=c.minimumClusterSize||2;this.X=c.maxZoom||e;this.m=c.styles||[];this.oa=c.imagePath||this.da;this.na=c.imageExtension||this.ca;this.ba=d;void 0!=c.zoomOnClick&&(this.ba=c.zoomOnClick);this.w=h;void 0!=c.averageCenter&&(this.w=c.averageCenter);if(!this.m.length){c=0;for(var f;f=this.va[c];c++)this.m.push({url:this.oa+(c+1)+"."+this.na,height:f,width:f})}this.a=
a;this.Y=this.a.W();var g=this;google.e.event.addListener(this.a,"zoom_changed",function(){var a=g.a.W();g.Y!=a&&(g.Y=a,g.p())});google.e.event.addListener(this.a,"idle",function(){g.l()});b&&b.length&&this.M(b,h)}l=m.prototype;l.da="http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/images/m";l.ca="png";l.extend=function(a,b){return function(a){for(var b in a.prototype)this.prototype[b]=a.prototype[b];return this}.apply(a,[b])};l.I=function(){this.J||(this.J=d,n(this))};
l.D=function(){};l.ha=function(){for(var a=this.s(),b=new google.e.B,c=0,f;f=a[c];c++)b.extend(f.g());this.a.ga(b)};l.H=j("m");l.s=j("b");l.ma=function(){return this.b.length};l.ua=function(a){this.X=a};l.T=j("X");l.P=function(a,b){for(var c=0,f=a.length,g=f;0!==g;)g=parseInt(g/10,10),c++;c=Math.min(c,b);return{text:f,index:c}};l.sa=function(a){this.P=a};l.R=j("P");l.M=function(a,b){for(var c=0,f;f=a[c];c++)p(this,f);b||this.l()};
function p(a,b){b.z=h;b.draggable&&google.e.event.addListener(b,"dragend",function(){b.z=h;a.Z()});a.b.push(b)}l.v=function(a,b){p(this,a);b||this.l()};function t(a,b){var c=-1;if(a.b.indexOf)c=a.b.indexOf(b);else for(var f=0,g;g=a.b[f];f++)if(g==b){c=f;break}if(-1==c)return h;b.a=e;a.b.splice(c,1);return d}l.qa=function(a,b){var c=t(this,a);return!b&&c?(this.p(),this.l(),d):h};l.ra=function(a,b){for(var c=h,f=0,g;g=a[f];f++)g=t(this,g),c=c||g;if(!b&&c)return this.p(),this.l(),d};l.la=function(){return this.h.length};
l.r=j("a");l.G=j("i");l.ta=function(a){this.i=a};l.F=function(a){var b=this.ja(),c=new google.e.L(a.U().k(),a.U().t()),f=new google.e.L(a.V().k(),a.V().t()),c=b.Q(c);c.x+=this.i;c.y-=this.i;f=b.Q(f);f.x-=this.i;f.y+=this.i;c=b.ia(c);b=b.ia(f);a.extend(c);a.extend(b);return a};l.fa=function(){this.p(d);this.b=[]};l.p=function(a){for(var b=0,c;c=this.h[b];b++)c.remove();for(b=0;c=this.b[b];b++)c.z=h,a&&(c.a=e);this.h=[]};
l.Z=function(){var a=this.h.slice();this.h.length=0;this.p();this.l();window.setTimeout(function(){for(var b=0,c;c=a[b];b++)c.remove()},0)};l.l=function(){n(this)};
function n(a){if(a.J)for(var b=new google.e.B(u(a.a).V(),u(a.a).U()),b=a.F(b),c=0,f;f=a.b[c];c++)if(!f.z&&b.contains(f.g())){var g=a,v=4E4,r=e;f.g();for(var z=0,q=void 0;q=g.h[z];z++){var k=q.S();if(k){var s=f.g();if(!k||!s)k=0;else var A=(s.k()-k.k())*Math.PI/180,B=(s.t()-k.t())*Math.PI/180,k=Math.sin(A/2)*Math.sin(A/2)+Math.cos(k.k()*Math.PI/180)*Math.cos(s.k()*Math.PI/180)*Math.sin(B/2)*Math.sin(B/2),k=6371*2*Math.atan2(Math.sqrt(k),Math.sqrt(1-k));k<v&&(v=k,r=q)}}r&&r.O.contains(f.g())?r.v(f):
(q=new w(g),q.v(f),g.h.push(q))}}function w(a){this.n=a;this.a=a.r();this.i=a.G();this.o=a.o;this.w=a.w;this.d=e;this.b=[];this.O=e;this.q=new x(this,a.H(),a.G())}l=w.prototype;
l.v=function(a){var b;a:if(this.b.indexOf)b=-1!=this.b.indexOf(a);else{b=0;for(var c;c=this.b[b];b++)if(c==a){b=d;break a}b=h}if(b)return h;this.d?this.w&&(c=this.b.length+1,b=(this.d.k()*(c-1)+a.g().k())/c,c=(this.d.t()*(c-1)+a.g().t())/c,this.d=new google.e.L(b,c),y(this)):(this.d=a.g(),y(this));a.z=d;this.b.push(a);b=this.b.length;b<this.o&&a.r()!=this.a&&(a.a=this.a);if(b==this.o)for(c=0;c<b;c++)this.b[c].a=e;b>=this.o&&(a.a=e);a=this.a.W();if((b=this.n.T())&&a>b)for(a=0;b=this.b[a];a++)b.a=this.a;
else this.b.length<this.o?C(this.q):(b=this.n.R()(this.b,this.n.H().length),this.q.d=this.d,a=this.q,a.K=b,a.Ca=b.text,a.za=b.index,a.c&&(a.c.innerHTML=b.text),b=Math.max(0,a.K.index-1),b=Math.min(a.m.length-1,b),b=a.m[b],a.wa=b.url,a.j=b.height,a.u=b.width,a.$=b.textColor,a.f=b.anchor,a.aa=b.textSize,a.N=b.backgroundPosition,this.q.show());return d};function u(a){var b=new google.e.B(a.d,a.d);a=a.s();for(var c=0,f;f=a[c];c++)b.extend(f.g());return b}
l.remove=function(){this.q.remove();this.b.length=0;delete this.b};l.ka=function(){return this.b.length};l.s=j("b");l.S=j("d");function y(a){var b=new google.e.B(a.d,a.d);a.O=a.n.F(b)}l.r=j("a");function x(a,b,c){a.n.extend(x,google.e.ea);this.m=b;this.Ba=c||0;this.C=a;this.d=e;this.a=a.r();this.K=this.c=e;this.A=h;this.a=this.a}l=x.prototype;
l.I=function(){this.c=document.createElement("DIV");if(this.A){var a=D(this,this.d);this.c.style.cssText=E(this,a);this.c.innerHTML=this.K.text}this.ya().Aa.appendChild(this.c);var b=this;google.e.event.xa(this.c,"click",function(){var a=b.C.n;google.e.event.Da(a,"clusterclick",b.C);a.ba&&b.a.ga(u(b.C))})};function D(a,b){var c=a.ja().Q(b);c.x-=parseInt(a.u/2,10);c.y-=parseInt(a.j/2,10);return c}l.D=function(){if(this.A){var a=D(this,this.d);this.c.style.top=a.y+"px";this.c.style.left=a.x+"px"}};
function C(a){a.c&&(a.c.style.display="none");a.A=h}l.show=function(){if(this.c){var a=D(this,this.d);this.c.style.cssText=E(this,a);this.c.style.display=""}this.A=d};l.remove=function(){this.a=e};l.pa=function(){this.c&&this.c.parentNode&&(C(this),this.c.parentNode.removeChild(this.c),this.c=e)};
function E(a,b){var c=[];c.push("background-image:url("+a.wa+");");c.push("background-position:"+(a.N?a.N:"0 0")+";");"object"===typeof a.f?("number"===typeof a.f[0]&&0<a.f[0]&&a.f[0]<a.j?c.push("height:"+(a.j-a.f[0])+"px; padding-top:"+a.f[0]+"px;"):c.push("height:"+a.j+"px; line-height:"+a.j+"px;"),"number"===typeof a.f[1]&&0<a.f[1]&&a.f[1]<a.u?c.push("width:"+(a.u-a.f[1])+"px; padding-left:"+a.f[1]+"px;"):c.push("width:"+a.u+"px; text-align:center;")):c.push("height:"+a.j+"px; line-height:"+a.j+
"px; width:"+a.u+"px; text-align:center;");c.push("cursor:pointer; top:"+b.y+"px; left:"+b.x+"px; color:"+(a.$?a.$:"black")+"; position:absolute; font-size:"+(a.aa?a.aa:11)+"px; font-family:Arial,sans-serif; font-weight:bold");return c.join("")}window.MarkerClusterer=m;m.prototype.addMarker=m.prototype.v;m.prototype.addMarkers=m.prototype.M;m.prototype.clearMarkers=m.prototype.fa;m.prototype.fitMapToMarkers=m.prototype.ha;m.prototype.getCalculator=m.prototype.R;m.prototype.getGridSize=m.prototype.G;
m.prototype.getExtendedBounds=m.prototype.F;m.prototype.getMap=m.prototype.r;m.prototype.getMarkers=m.prototype.s;m.prototype.getMaxZoom=m.prototype.T;m.prototype.getStyles=m.prototype.H;m.prototype.getTotalClusters=m.prototype.la;m.prototype.getTotalMarkers=m.prototype.ma;m.prototype.redraw=m.prototype.l;m.prototype.removeMarker=m.prototype.qa;m.prototype.removeMarkers=m.prototype.ra;m.prototype.resetViewport=m.prototype.p;m.prototype.repaint=m.prototype.Z;m.prototype.setCalculator=m.prototype.sa;
m.prototype.setGridSize=m.prototype.ta;m.prototype.setMaxZoom=m.prototype.ua;m.prototype.onAdd=m.prototype.I;m.prototype.draw=m.prototype.D;w.prototype.getCenter=w.prototype.S;w.prototype.getSize=w.prototype.ka;w.prototype.getMarkers=w.prototype.s;x.prototype.onAdd=x.prototype.I;x.prototype.draw=x.prototype.D;x.prototype.onRemove=x.prototype.pa;